# Generated by Django 5.1.4 on 2025-03-25 06:29

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="competencymatrixitem",
            index=models.Index(
                django.db.models.functions.text.Lower("sheet"),
                name="cmi_sheet_idx",
            ),
        ),
    ]
