# Generated by Django 5.1.4 on 2025-03-26 13:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0002_alter_competencymatrixitem_resources_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CompetencyMatrixItem",
            new_name="CompetencyMatrixItemModel",
        ),
        migrations.RenameModel(
            old_name="Resource",
            new_name="ResourceModel",
        ),
        migrations.AlterModelTable(
            name="resourcemodel",
            table="competency_matrix_resources",
        ),
    ]
