# Generated by Django 5.1.4 on 2025-03-23 14:18

import django.utils.timezone
import mdeditor.fields
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("url", models.URLField(verbose_name="Ссылка")),
                (
                    "context",
                    mdeditor.fields.MDTextField(
                        blank=True,
                        verbose_name="Контекст, зачем этот ресурс был сюда добавлен",
                    ),
                ),
            ],
            options={
                "verbose_name": "Внешние ресурс",
                "verbose_name_plural": "Внешние ресурсы",
            },
        ),
        migrations.CreateModel(
            name="CompetencyMatrixItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("draft", "draft"), ("published", "published")],
                        default="draft",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        verbose_name="Статус изменен",
                    ),
                ),
                ("question", models.CharField(max_length=255, verbose_name="Вопрос")),
                ("answer", mdeditor.fields.MDTextField(blank=True, verbose_name="Ответ")),
                (
                    "interview_expected_answer",
                    mdeditor.fields.MDTextField(
                        blank=True,
                        verbose_name="Ответ, который ожидают на интервью",
                    ),
                ),
                ("sheet", models.CharField(max_length=255, verbose_name="Лист")),
                ("section", models.CharField(blank=True, max_length=255, verbose_name="Раздел")),
                (
                    "subsection",
                    models.CharField(blank=True, max_length=255, verbose_name="Подраздел"),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Уровень компетенции",
                    ),
                ),
                (
                    "resources",
                    models.ManyToManyField(
                        blank=True,
                        to="db.resource",
                        verbose_name="Внешние ресурсы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент матрицы компетенций",
                "verbose_name_plural": "Элементы матрицы компетенций",
                "db_table": "competency_matrix_item",
                "ordering": ["subsection", "section", "grade", "question"],
            },
        ),
    ]
