HTTP_OK = 200
HTTP_NO_CONTENT = 204
HTTP_TOO_MANY_REQUESTS = 429

WAIT_TIME_MIN_SECONDS = 0.2
WAIT_TIME_MAX_SECONDS = 1.0

TASK_WEIGHT_HEALTHCHECK = 2
TASK_WEIGHT_I18N_LANGUAGES = 2
TASK_WEIGHT_I18N_BUNDLE = 2
TASK_WEIGHT_ARTICLES_LIST = 4
TASK_WEIGHT_ARTICLES_TREE = 2
TASK_WEIGHT_ARTICLE_DETAIL = 3
TASK_WEIGHT_MATRIX_SHEETS = 3
TASK_WEIGHT_MATRIX_ITEMS = 3
TASK_WEIGHT_MATRIX_ITEM_DETAIL = 3
TASK_WEIGHT_MATRIX_QUESTION_SUGGESTION = 1
TASK_WEIGHT_SPA_ROOT = 1

DISCOVERY_ARTICLES_PAGE_SIZE = 100
ARTICLES_LIST_PAGE_SIZE = 10
SEEDED_ENTITY_PREFIX = "perf-seed-"
MATRIX_QUESTION_SUGGESTION_PREFIX = "Locust matrix suggestion"
MATRIX_QUESTION_SUGGESTION_SUCCESS_STATUSES = frozenset(
    {HTTP_NO_CONTENT, HTTP_TOO_MANY_REQUESTS},
)
