# Generated by Django 5.1.3 on 2024-12-04 14:54

import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Уровень компетенции',
                'verbose_name_plural': 'Уровень компетенций',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка')),
                (
                    'context',
                    mdeditor.fields.MDTextField(
                        blank=True, verbose_name='Контекст, зачем этот ресурс был сюда добавлен'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Внешние ресурс',
                'verbose_name_plural': 'Внешние ресурсы',
            },
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Лист',
                'verbose_name_plural': 'Листы',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                (
                    'sheet',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='competency_matrix.sheet',
                        verbose_name='Лист',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                (
                    'section',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='competency_matrix.section',
                        verbose_name='Раздел',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Подраздел',
                'verbose_name_plural': 'Подразделы',
            },
        ),
        migrations.CreateModel(
            name='CompetencyMatrixItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'status',
                    model_utils.fields.StatusField(
                        choices=[('draft', 'draft'), ('published', 'published')],
                        default='draft',
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name='Статус',
                    ),
                ),
                (
                    'status_changed',
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor='status',
                        verbose_name='Статус изменен',
                    ),
                ),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', mdeditor.fields.MDTextField(blank=True, verbose_name='Ответ')),
                (
                    'interview_expected_answer',
                    mdeditor.fields.MDTextField(
                        blank=True, verbose_name='Ответ, который ожидают на интервью'
                    ),
                ),
                (
                    'grade',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='competency_matrix.grade',
                        verbose_name='Уровень компетенции',
                    ),
                ),
                (
                    'resources',
                    models.ManyToManyField(
                        blank=True, to='competency_matrix.resource', verbose_name='Внешние ресурсы'
                    ),
                ),
                (
                    'subsection',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='competency_matrix.subsection',
                        verbose_name='Подраздел',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Элемент матрицы компетенций',
                'verbose_name_plural': 'Элементы матрицы компетенций',
                'db_table': 'competency_matrix_item',
                'ordering': ['subsection', 'subsection__section', 'grade', 'question'],
            },
        ),
    ]
