name: Deploy to Remote Server

on:
  workflow_call:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    name: "Docker build and push"
    uses: ./.github/workflows/_docker.yaml
    secrets: inherit

  infrastructure:
    name: "Push infrastructure to remote server"
    needs: docker
    uses: ./.github/workflows/_infrastructure.yaml
    secrets: inherit

  restart:
    name: "Restart application on remote server"
    needs: infrastructure
    uses: ./.github/workflows/_restart.yaml
    secrets: inherit
